-- Lisää DROP TABLE lauseet tähän tiedostoon
-- DROP TABLE IF EXISTS Member CASCADE; 
DROP TABLE IF EXISTS Driver CASCADE;
DROP TABLE IF EXISTS Team CASCADE;
DROP TABLE IF EXISTS Track CASCADE;
DROP TABLE IF EXISTS Race CASCADE;
